### PR TITLE
Index-page-v1

### PR DESCRIPTION
**Pull request by viktor472**
Hi please comment if there is something unclear and something I can improve 🍔

### CODE REVIEW

**Comment by AD1121** [comment]
Can you add contact.html in the contanct link?
also remove home page
Add Contact Us instead of just Contact

**Comment by viktor472** [comment]
ok will fix the contact link. 

does it not? it works for me. will check when my pc is upp and running again!

**Comment by AD1121** [comment]
let me check the code

**Comment by AD1121** [comment]
seems good with code. 
To link it have to be contact.html in the a tag. If its fixed then its ready for merge i think

**Pull request merged**
